# Generated by Django 5.0.6 on 2024-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/images'),
        ),
    ]
