services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    
    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: ./wait-for db:3306 && python manage.py runserver 0.0.0.0:8000
    volumes:
      - app: ./code
      
    restart: always

    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  app:
  mysql_data: